// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: internal/proto/candles.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []string               `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"` // e.g., ["BTCUSDT", "ETHUSDT"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_internal_proto_candles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_candles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_candles_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetPairs() []string {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type CandleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pair          string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix ms, start of interval
	Open          float64                `protobuf:"fixed64,3,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,4,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,5,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,6,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,7,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandleResponse) Reset() {
	*x = CandleResponse{}
	mi := &file_internal_proto_candles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandleResponse) ProtoMessage() {}

func (x *CandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_candles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandleResponse.ProtoReflect.Descriptor instead.
func (*CandleResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_candles_proto_rawDescGZIP(), []int{1}
}

func (x *CandleResponse) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *CandleResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CandleResponse) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *CandleResponse) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *CandleResponse) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *CandleResponse) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *CandleResponse) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

var File_internal_proto_candles_proto protoreflect.FileDescriptor

const file_internal_proto_candles_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/candles.proto\x12\acandles\"(\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05pairs\x18\x01 \x03(\tR\x05pairs\"\xaa\x01\n" +
	"\x0eCandleResponse\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04open\x18\x03 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x04 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x05 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x06 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\a \x01(\x01R\x06volume2R\n" +
	"\rCandleService\x12A\n" +
	"\tSubscribe\x12\x19.candles.SubscribeRequest\x1a\x17.candles.CandleResponse0\x01B\x10Z\x0einternal/protob\x06proto3"

var (
	file_internal_proto_candles_proto_rawDescOnce sync.Once
	file_internal_proto_candles_proto_rawDescData []byte
)

func file_internal_proto_candles_proto_rawDescGZIP() []byte {
	file_internal_proto_candles_proto_rawDescOnce.Do(func() {
		file_internal_proto_candles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_candles_proto_rawDesc), len(file_internal_proto_candles_proto_rawDesc)))
	})
	return file_internal_proto_candles_proto_rawDescData
}

var file_internal_proto_candles_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_candles_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: candles.SubscribeRequest
	(*CandleResponse)(nil),   // 1: candles.CandleResponse
}
var file_internal_proto_candles_proto_depIdxs = []int32{
	0, // 0: candles.CandleService.Subscribe:input_type -> candles.SubscribeRequest
	1, // 1: candles.CandleService.Subscribe:output_type -> candles.CandleResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_candles_proto_init() }
func file_internal_proto_candles_proto_init() {
	if File_internal_proto_candles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_candles_proto_rawDesc), len(file_internal_proto_candles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_candles_proto_goTypes,
		DependencyIndexes: file_internal_proto_candles_proto_depIdxs,
		MessageInfos:      file_internal_proto_candles_proto_msgTypes,
	}.Build()
	File_internal_proto_candles_proto = out.File
	file_internal_proto_candles_proto_goTypes = nil
	file_internal_proto_candles_proto_depIdxs = nil
}
