FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o client ./cmd/client

FROM alpine:latest
COPY --from=builder /app/client /usr/bin/client
CMD ["client", "--pairs=BTCUSDT,ETHUSDT"]