FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o /app/client ./cmd/client

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/client /app/
CMD ["/app/client", "--pairs=BTCUSDT,ETHUSDT,SOLUSDT", "--retry=3", "--max-retries=20"]